config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  root to: 'home#top'
  get "/home/about" => "home#about"
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]

  resources :books, except: [:new] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  get 'follow/:id' => 'relationships#follow_index', as:'follows'
  get 'follower/:id' => 'relationships#follower_index', as:'followers'
  post 'follow/:id' => 'relationships#create', as:'follow'
  post 'unfollow/:id' => 'relationships#destroy', as:'unfollow'

  get '/search' => 'search#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true,
                   length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id:user.id).exists?
  end

  def Book.search(search, user_or_book, how_search)
    if user_or_book == "2"
      if how_search == "1"
        Book.where(['title LIKE ?', "%#{search}%"])
      elsif how_search == "2"
        Book.where(['title LIKE ?', "%#{search}"])
      elsif how_search == "3"
        Book.where(['title LIKE ?', "#{search}%"])
      elsif how_search == "4"
        Book.where(['title LIKE ?', "#{search}"])
      else
        Book.all
      end
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name:"User"
  belongs_to :followed, class_name:"User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower, class_name:"Relationship", foreign_key:"follower_id", dependent: :destroy
  has_many :followed, class_name:"Relationship", foreign_key:"followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id:user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id:user_id).destroy
  end

  # フォロー確認を行う
  def following?(user)
    following_user.include?(user)
  end

  def User.search(search, user_or_book, how_search)
    if user_or_book == "1"
      if how_search == "1"
        User.where(['name LIKE ?', "%#{search}%"])
      elsif how_search == "2"
        User.where(['name LIKE ?', "%#{search}"])
      elsif how_search == "3"
        User.where(['name LIKE ?', "#{search}%"])
      elsif how_search == "4"
        User.where(['name LIKE ?', "#{search}"])
      else
        User.all
      end
    end
  end

  attachment :profile_image

  validates :name, uniqueness: true,
                   length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!,except: [:top, :about]
    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      user_path(resource)
    end

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
    end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :check_user, only: [:edit, :update]

  def check_user
    book=Book.find(params[:id])
    unless book.user == current_user
      redirect_to books_path
    end
  end

  def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    @user=current_user
    @books=Book.all
    if @book.save
      flash[:success] = "You have created book successfully"
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def index
    @book=Book.new
    @books=Book.all
    @user=current_user
  end

  def show
    @book=Book.find(params[:id])
    @book_comment=BookComment.new
    @newbook=Book.new
    @user=User.find(@book.user_id)
  end

  def edit
    @book=Book.find(params[:id])
  end

  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
       flash[:success] = "You have updated book successfully"
       redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id:@book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id:@book.id)
    favorite.destroy
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_user.follow(params[:id])
    redirect_back(fallback_location:root_path)
  end

  def follow_index
    @users = current_user.following_user
  end

  def follower_index
    @users = current_user.follower_user
  end

  def destroy
    current_user.unfollow(params[:id])
    redirect_back(fallback_location:root_path)
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @user_or_book = params[:option]
    @how_search = params[:choice]
    if @user_or_book == "1"
      @users = User.search(params[:search], @user_or_book, @how_search)
    else
      @books = Book.search(params[:search], @user_or_book, @how_search)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_user, only: [:edit, :update]

  def check_user
    user=User.find(params[:id])
    unless user == current_user
      redirect_to user_path(current_user.id)
    end
  end

  def index
    @users=User.all
    @book=Book.new
    @user=current_user
  end

  def show
    @user=User.find(params[:id])
    @book=Book.new
    @books=@user.books
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "You have updated user successfully"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.js.erb
$("#comments_area").html("<%= j(render 'books/comments', book: @book) %>");
$("textarea").val("");

app/views/book_comments/destroy.js.erb
$("#comments_area").html("<%= j(render 'books/comments', book: @book) %>");
$("textarea").val("");

app/views/books/_book.html.erb
<% if book.favorited_by?(current_user) %>
<p>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    ❤<%= book.favorites.count %>いいね
  <% end %>
</p>
<% else %>
<p>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    ❤<%= book.favorites.count %>いいね
  <% end %>
</p>
<% end %>

app/views/books/_comments.html.erb
<% book.book_comments.each do |book_comment| %>
<tr>
  <td>
    <%= link_to user_path(book_comment.user), local:true do %>
      <%= attachment_image_tag book_comment.user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg", size:'30x30' %>
      <br>
      <%= book_comment.user.name %>
    <% end %>
  </td>
  <td><%= book_comment.comment %></td>
    <% if book_comment.user == current_user %>
      <td><%= link_to "Destroy", book_book_comment_path(book_comment.book,book_comment), method: :delete, remote:true, class: "btn btn-danger", data:{confirm:"本当に消しますか?"}  %></td>
    <% end %>
</tr>
<% end %>

app/views/books/_post.html.erb
<% if book.favorited_by?(current_user) %>
<p>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    ❤<%= book.favorites.count %>いいね
  <% end %>
</p>
<% else %>
<p>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    ❤<%= book.favorites.count %>いいね
  <% end %>
</p>
<% end %>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>
      <% if @book.errors.any? %>
        <%= @book.errors.count %>error prohibited this obj from being saved:<br>
        <% @book.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
<%= form_with model:@book, local:true do |f| %>
  <label for="book-title">Title</label><br>
  <%= f.text_field :title %><br>
  <label for="book-opinion">Opinion</label><br>
  <%= f.text_area :body %><br>
  <%= f.submit 'Update Book', class: "btn btn-success" %>
<% end %><br>
<%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path(@books) %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    <% if @book.errors.any? %>
      <%= @book.errors.count %>error prohibited this obj from being saved:<br>
        <% @book.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
    <% end %>
    <%= render 'users/list', user: @user %>

      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
          <label for="book-title">Title</label>
          <br>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <label for="book-opinion">Opinion</label>
          <br>
          <%= f.text_area :body %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', class: "btn btn-success" %>
        </div>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th colspan="1"></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.id) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg", size:'30x30' %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td class="book_<%= book.id %>">
　　　　　　　  <%= render "book", book: book %>
              </td>
              <td>
                <p>コメント数<%= book.book_comments.count %></p>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    <%= render 'users/list', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @newbook, local:true do |f| %>
        <div class="form-group">
          <label for="book-title">Title</label>
          <br>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <label for="book-opinion">Opinion</label>
          <br>
          <%= f.text_area :body %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book' %>
        </div>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg" %>
                <br>
                <%= @user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@user) do %>
                <%= @book.title %>
              <% end %>
                <%= @book.body %>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to "Edit", edit_book_path(@book), class: "btn btn-success" %>
                <%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-danger", data:{confirm:"本当に消しますか?"} %>
              <% end %>
            </td>
            <td class="book_<%= @book.id %>">
              <%= render 'book', book:@book %>
            </td>
            <td>
              <p>コメント数:<%= @book.book_comments.count %></p>
            </td>
          </tr>
        </tbody>
      </table>
      <table id="comments_area">
        <%= render 'comments', book:@book, user:@user %>
      </table>
      <table>
        <%= form_with model:[@book, @book_comment], remote:true do |f| %>
  　　　  　　<%= f.text_area :comment, rows:'5', placeholder: "コメントをここに" %>
          <%= f.submit "送信" %>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/favorites/create.js.erb
$(".book_<%= @book.id %>").html("<%= j(render 'books/book', book: @book) %>");

app/views/favorites/destroy.js.erb
$(".book_<%= @book.id %>").html("<%= j(render 'books/book', book: @book) %>");

app/views/home/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to <i class="fas fa-book"></i><strong>Bookers!</strong>
    </h1>
  </div>
</div>

app/views/home/top.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
    <h1>
      welcome to<i class="fas fa-book"></i><strong>Bookers!!</strong>
    </h1>
      <p>
        In<i class="fas fa-book"></i><strong>Bookers,</strong>
      </p>
        <p>you can share and exchange your opinions , inpressions , and emotions<br>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <p><%= link_to 'Log in', new_user_session_path, method: :get, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %></p>
          </div>
          <div class="row">
            <p><%= link_to 'Sign Up', new_user_registration_path, method: :get, class: 'btn btn-success btn-sm btn-block sign_up' %></p>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/relationships/follow_index.html.erb
      <h2>Follow Users</h2>
      <% if @users.present? %>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg" %></td>
                <td><%= user.name %></td>
                <td>フォロー数：<%= user.follower.count %></td>
                <td>フォロワー数：<%= user.followed.count %></td>
                <td><%= link_to "Show", user_path(user), method: :get %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>ユーザーはいません</p>
      <% end %>

app/views/relationships/follower_index.html.erb
      <h2>Follower Users</h2>
      <% if @users.present? %>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg" %></td>
                <td><%= user.name %></td>
                <td>フォロー数：<%= user.follower.count %></td>
                <td>フォロワー数：<%= user.followed.count %></td>
                <td><%= link_to "Show", user_path(user), method: :get %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>ユーザーはいません</p>
      <% end %>

app/views/relationships/index.html.erb
      <h2>Follow Users</h2>
      <% if @users.present? %>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg" %></td>
                <td><%= user.name %></td>
                <td>フォロー数：<%= user.follower.count %></td>
                <td>フォロワー数：<%= user.followed.count %></td>
                <td><%= link_to "Show", user_path(user), method: :get %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>ユーザーはいません</p>
      <% end %>

app/views/search/search.html.erb
<% if @user_or_book == "1" %>
  <h1>Users search for "<%= params[:search] %>"</h1>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user_path(user), method: :get %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

<% elsif @user_or_book == "2" %>
  <h1>Books search for "<%= params[:search] %>"</h1>
  <table class="table">
    <thead>
      <tr>
        <th colspan="1"></th>
        <th>Title</th>
        <th>Opinion</th>
      </tr>
    </thead>
    <tbody>
    <% @books.each do |book| %>
    <thead>
      <tr>
        <td>
          <%= link_to user_path(book.id) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg", size:'30x30' %>
          <% end %>
        </td>
        <td>
          <%= link_to book_path(book.id) do %>
            <%= book.title %>
          <% end %>
        </td>
        <td>
          <%= book.body %>
        </td>
      </tr>
    </thead>
    <% end %>
    </tbody>
  </table>
<% else %>
<% end %>

app/views/users/_list.html.erb
      <h2>User info</h2>
      <table class="table">
        <tbody>
          <tr>
            <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
          </tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th>
              <%= link_to follows_path(user) do %>
                <%= user.follower.count %>
              <% end %>
            </th>
          </tr>
          <tr>
            <th>followers</th>
            <th>
              <%= link_to followers_path(user) do %>
                <%= user.followed.count %>
              <% end %>
            </th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <% if user == current_user %>
          <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block", method: :get do %>
            <i class="fas fa-user-cog"></i>
          <% end %>
        <% end %>
      </div>
      <div>
        <% unless user == current_user %>
          <% if current_user.following?(user) %>
            <%= link_to 'フォロー外す', unfollow_path(user.id), method: :post, class: 'btn btn-info' %>
          <% else %>
            <%= link_to 'フォローする', follow_path(user.id), method: :post, class: 'btn btn-success' %>
          <% end %>
        <% end %>
      </div>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if @user.errors.any? %>
        <%= @user.errors.count %>errors prohibited this obj from being saved:<br>
        <% @user.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
<%= form_with model:@user, local:true do |f| %>
  <label for="inputName">Name</label><br>
  <%= f.text_field :name, id:"inputName" %><br>
  <label for="inputImage">Image</label><br>
  <%= f.attachment_field :profile_image %><br>
  <label for="InputIntroduction">Introduction</label><br>
  <%= f.text_area :introduction %><br>
  <%= f.submit "Update User", class: "btn btn-secondary" %>
<% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    <%= render 'users/list', user: @user %>

      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
          <label for="book-title">Title</label>
          <br>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <label for="book-opinion">Opinion</label>
          <br>
          <%= f.text_area :body %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book', class: "btn btn-success" %>
        </div>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg", size:'30x30' %></td>
              <td><%= user.name %></td>
              <td>フォロー数：<%= user.follower.count %></td>
              <td>フォロワー数：<%= user.followed.count %></td>
              <td>
                <% unless user == current_user %>
                  <% if current_user.following?(user) %>
                    <%= link_to 'フォロー外す', unfollow_path(user.id), method: :post %>
                  <% else %>
                    <%= link_to 'フォローする', follow_path(user.id), method: :post %>
                  <% end %>
                <% end %>
              </td>
              <td><%= link_to "Show", user_path(user), method: :get %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    <%= render 'users/list', user: @user %>

      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
          <label for="book-title">Title</label>
          <br>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <label for="book-opinion">Opinion</label>
          <br>
          <%= f.text_area :body %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Book' %>
        </div>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user_id) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td>
                <p>コメント数：<%= book.book_comments.count %></p>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>