config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  root to: 'home#top'
  get "/home/about" => "home#about"
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]

  resources :books, except: [:new] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  get 'follow/:id' => 'relationships#follow_index', as:'follows'
  get 'follower/:id' => 'relationships#follower_index', as:'followers'
  post 'follow/:id' => 'relationships#create', as:'follow'
  post 'unfollow/:id' => 'relationships#destroy', as:'unfollow'

  get '/search' => 'search#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true,
                   length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id:user.id).exists?
  end

  def Book.search(search, user_or_book, how_search)
    if user_or_book == "2"
      if how_search == "1"
        Book.where(['title LIKE ?', "%#{search}%"])
      elsif how_search == "2"
        Book.where(['title LIKE ?', "%#{search}"])
      elsif how_search == "3"
        Book.where(['title LIKE ?', "#{search}%"])
      elsif how_search == "4"
        Book.where(['title LIKE ?', "#{search}"])
      else
        Book.all
      end
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name:"User"
  belongs_to :followed, class_name:"User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower, class_name:"Relationship", foreign_key:"follower_id", dependent: :destroy
  has_many :followed, class_name:"Relationship", foreign_key:"followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id:user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id:user_id).destroy
  end

  # フォロー確認を行う
  def following?(user)
    following_user.include?(user)
  end

  def User.search(search, user_or_book, how_search)
    if user_or_book == "1"
      if how_search == "1"
        User.where(['name LIKE ?', "%#{search}%"])
      elsif how_search == "2"
        User.where(['name LIKE ?', "%#{search}"])
      elsif how_search == "3"
        User.where(['name LIKE ?', "#{search}%"])
      elsif how_search == "4"
        User.where(['name LIKE ?', "#{search}"])
      else
        User.all
      end
    end
  end

  attachment :profile_image

  validates :name, uniqueness: true,
                   length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!,except: [:top, :about]
    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      user_path(resource)
    end

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :check_user, only: [:edit, :update]

  def check_user
    book=Book.find(params[:id])
    unless book.user == current_user
      redirect_to books_path
    end
  end

  def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    @user=current_user
    @books=Book.all
    if @book.save
      flash[:success] = "You have created book successfully"
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def index
    @book=Book.new
    @books=Book.all
    @user=current_user
  end

  def show
    @book=Book.find(params[:id])
    @book_comment=BookComment.new
    @newbook=Book.new
    @user=User.find(@book.user_id)
  end

  def edit
    @book=Book.find(params[:id])
  end

  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
       flash[:success] = "You have updated book successfully"
       redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id:@book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id:@book.id)
    favorite.destroy
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @user_or_book = params[:option]
    @how_search = params[:choice]
    if @user_or_book == "1"
      @users = User.search(params[:search], @user_or_book, @how_search)
    else
      @books = Book.search(params[:search], @user_or_book, @how_search)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_user, only: [:edit, :update]

  def check_user
    user=User.find(params[:id])
    unless user == current_user
      redirect_to user_path(current_user.id)
    end
  end

  def index
    @users=User.all
    @book=Book.new
    @user=current_user
  end

  def show
    @user=User.find(params[:id])
    @book=Book.new
    @books=@user.books
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "You have updated user successfully"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/6372faa667.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", root_path, class: 'navbar-brand' %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li>
              <%= link_to user_path(current_user.id), class: "fas fa-home nav-link text-light" do %>
                Home
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class: "fas fa-users nav-link text-light" do %>
                Users
              <% end %>
            </li>
            <li>
              <%= link_to books_path, class: "fas fa-book-open nav-link text-light" do %>
                Books
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, class: "fas fa-sign-out-alt nav-link text-light", method: :delete do %>
                logout
              <% end %>
            </li>
            <% else %>
            <li>
              <%= link_to root_path, class: "fas fa-home nav-link text-light" do %>
                Home
              <% end %>
            </li>
            <li>
              <%= link_to "/home/about", class: "fas fa-link nav-link text-light" do %>
                About
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class: "fas fa-user-plus nav-link text-light" do %>
                sign up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" do %>
                login
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <% if user_signed_in? %>
    <div class="search">
      <%= form_tag(search_path, :method => 'get') do %>
        <%= text_field_tag :search %>
        <%= select_tag(:option, options_for_select([["user", "1"],["book", "2"]])) %>
        <%= select_tag(:choice, options_for_select([["部分一致", "1"],["後方一致", "2"],["前方一致", "3"],["完全一致", "4"]])) %>
        <%= submit_tag '検索', :name => nil %>
      <% end %>
    </div>
    <% end %>

    <% flash.each do |message_type, message| %>
      <%= content_tag :div, message, class: message_type %>
    <% end %>

    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>